version: '3.8'

services:
  redis-proxy:
    image: jclavoie/redis-proxy:0.0.1-SNAPSHOT
    depends_on:
      - "redis"
    ports:
      - "8080:8080"
    networks:
      - my-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
    name: redis-proxy-network