version: '3.8'

services:
  redis-proxy:
    image: jclavoie/redis-proxy:0.0.1-SNAPSHOT
    depends_on:
      - "redis"
    ports:
      - "18080:8080"
  redis:
    image: "redis:alpine"
    ports:
      - "16379:6379"