version: '3.8'

services:
  redis-proxy:
    image: jclavoie/redis-proxy:0.0.1-SNAPSHOT
    depends_on:
      - "redis"
    ports:
      - "18080:8080"
      - "16379:6379"
    networks:
      - my-network
    environment:
      - LOCAL_CACHE_SIZE=${cache_size}
      - LOCAL_CACHE_TTL_SECONDS=${cache_ttl}
      - MAX_CONCURRENT_REQUESTS=${max_concurrent_requests}
      #- TCP_SERVER_HOSTNAME=${tcp_server_hostname}
      #- TCP_SERVER_PORT=${tcp_server_port}

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
    name: redis-proxy-network