version: '3.8'

services:
  redis-proxy:
    image: jclavoie/redis-proxy:0.0.1-SNAPSHOT
    depends_on:
      - "redis"
    # Uncomment to expose services outside of the docker-compose network
    #ports:
    #  - "18080:8080"
    #  - "16379:6379"
    networks:
      - my-network
    environment:
      - LOCAL_CACHE_SIZE=${proxy_service_cache_size}
      - LOCAL_CACHE_TTL_SECONDS=${proxy_service_cache_ttl}
      - MAX_CONCURRENT_REQUESTS=${proxy_service_max_concurrent_requests}
      - TCP_SERVER_HOSTNAME=${proxy_service_tcp_hostname}
      - TCP_SERVER_PORT=${proxy_service_tcp_port}
      - REDIS_SERVICE_NAME=${redis_service_name}
      - REDIS_SERVICE_PORT=${redis_service_port}

  redis:
    image: "redis:alpine"
    # Uncomment to expose services outside of the docker-compose network
    #ports:
    #  - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
    name: redis-proxy-network