spring:
  application:
    name: redis-proxy
  profiles:
    active: default, local
  main:
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: 5s

server:
  shutdown: graceful

application:
  redis-proxy:
    cache.size: 50
    cache.ttl_second: 20

# Actuators
management:
  server.port: 8081
  endpoints.web:
    exposure.include: "*"
  metrics:
    enable.jvm: true
  # Uses the telegraf sidecar port for health
  endpoint:
    health:
      show-details: always
      probes.enabled: true

# /actuator/info properties
info:
  groupId: "@project.groupId@"
  artifactId: "@project.artifactId@"
  version: "@project.version@"
  name: "@project.name@"
  description: "@project.description@"

springdoc:
  api-docs.enabled: true
  use-management-port: true
  show-actuator: true

---
spring:
  config.activate.on-profile: local
  redis:
    database: 0
    host: "127.0.0.1"
    port: "16379"
    timeout: 60000

---
spring:
  config.activate.on-profile: compose
  redis:
    database: 0
    host: "redis"
    port: "6379"
    timeout: 60000

---
# Actuator properties https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html
management:
  server.port: 8081
  metrics:
    enable:
      all: false
      jvm: true
      http: true
    distribution:
      slo:
        http:
          server.requests: 100ms,200ms,500ms,1000ms,2000ms,3000ms,5000ms,8000ms
          client.requests: 100ms,200ms,500ms,1000ms,2000ms,3000ms,5000ms,8000ms
  # Uses the telegraf sidecar port for health
  endpoint:
    health:
      show-details: always
      probes.enabled: true
