version: '3.8'

services:
  redis-proxy:
    image: jclavoie/python-e2e:0.0.1-SNAPSHOT
    networks:
      - my-network
    environment:
      - LOCAL_CACHE_SIZE=${cache_size}
      - LOCAL_CACHE_TTL_SECONDS=${cache_ttl}

networks:
  my-network:
    name: redis-proxy-network